### ISSUE TITLE
wallet run error

### ISSUE THREAD

**Issue by liwei-github** [cryptoeconomicslab/wallet#54]
When I ran the source in https://github.com/cryptoeconomicslab/wallet , got errors as below. Can someone tell me why?

-----------------------
../node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/home/liw/disk/plasma-0508/wallet/node_modules/node-fetch/lib'
{ Error: Cannot find module 'XMLHttpRequest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.xmlhttprequest (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:53541:18)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/utils/web.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:25130:24)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/providers/base-provider.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:18103:13)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/providers/index.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:19791:23)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/ethers.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:17767:30)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/index.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:17821:27)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module 'XMLHttpRequest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.xmlhttprequest (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:53541:18)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/utils/web.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:25130:24)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/providers/base-provider.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:18103:13)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/providers/index.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:19791:23)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/ethers.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:17767:30)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/index.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:17821:27)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module 'XMLHttpRequest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.xmlhttprequest (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:53541:18)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/utils/web.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:25130:24)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/providers/base-provider.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:18103:13)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/providers/index.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:19791:23)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/ethers.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:17767:30)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/index.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:17821:27)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module 'XMLHttpRequest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.xmlhttprequest (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:53541:18)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/utils/web.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:25130:24)
    at __webpack_require__ (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:23:31)
    at Object.../node_modules/ethers/providers/base-provider.js (/home/liw/disk/plasma-0508/wallet/src/.next/server/static/development/pages/_app.js:18103:13)
Compiled with warnings.

../node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/home/liw/disk/plasma-0508/wallet/node_modules/node-fetch/lib'

**Comment by tkmct** [comment]
@liwei-github 
Thank you for reporting.
Can you give me your running environment?

I only see the warnings and still possible to build and run the project.

**Comment by liwei-github** [comment]
At the chrome side , there is error "Internal Server Error".
OS : Ubuntu 18.04.1
Node : v10.15.3
NPM: 6.9.0

Thanks.

**Comment by tkmct** [comment]
Thank you, I'll take a look at it.

**Comment by liwei-github** [comment]
@tkmct 
How is it going?

**Comment by tkmct** [comment]
Sorry for replying late.
I reproduced the problem and trying to solve it.
It's webpack externals related issue. Please wait for a moment for us to solve the problem.
